/** 
*This template was generated by littleIDE
**/

package algo;
/** 
*
*@author CaS
**/

public class clase{


/**
*Attributes
*
*	For example:
*
*		private String att;
*		private int num;
**/





/**
*Methods
*
*	For example:
*
*		public void doSomething(){
*			//instructions
*		}
*		public int getSomething(){
*			//instructions
*			int x=3;
*			return x;
*		}
**/


}

//End Class
