/** 
*This template was generated by ECO-IDE
**/

package Mundo;

import DTO.Profesor;
import MongoDB.MongoDB;
import java.util.ArrayList;

/** 
*
*@author cas@
**/

public class ControlMundo {

    MongoDB mongo = new MongoDB();
    public ControlMundo(){

    }

    public boolean validarContrasena(String usuario, String contrasena) {
        return mongo.validarContrasena(usuario, contrasena);
    }

    public ArrayList<Profesor> getProfesores() {
        return mongo.getProfesores();
    }

    public boolean agregarProfesor(String nombre , String codigo) {
        Profesor p = new Profesor();
        p.setCodigo(codigo);
        p.setNombre(nombre);
        return mongo.agregarProfesor(p);
    }
    
    public static void main(String [] args){
        ControlMundo cm = new ControlMundo();
        boolean valido = cm.validarContrasena("cas@", "xxxx");
        System.out.println("Validar pass "+valido);
        if (valido) {
            System.out.println("Consultar profesores : "+cm.getProfesores().toString());
            //System.out.println("Agregar profesor : "+cm.agregarProfesor("Wilson", "1150010"));
        }
    }

    
}