/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package $_p_a_c_k_$_R_e_d_i_r_e_c_t_$_p_a_c_k_$;

/**
 *
 * @author CaS
 */

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author CaS
 */
public class PanelEjecucion extends javax.swing.JPanel {

    /** Creates new form disenoGrafico */
    public PanelEjecucion() {
        initComponents();
    }

    public void addSalida(String msg){
        this.jtaSalida.setText(this.jtaSalida.getText()+msg);
    }
    public void addError(String msg){
        this.jtaError.setText(this.jtaError.getText()+msg);
    }
    public void addEntrada(String msg){
            this.jtaEntrada.setText(this.jtaEntrada.getText()+msg);
    }

    public JButton getBotonEjecutar(){
        return this.jButtonEjecutar;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTabbedPaneConsola = new JTabbedPane();
        jPanelConsolaSalida = new JPanel();
        jScrollPaneConsolaSalida = new JScrollPane();
        jtaSalida = new JTextArea();
        jPanelConsolaEntrada = new JPanel();
        jScrollPaneConsolaEntrada = new JScrollPane();
        jtaEntrada = new JTextArea();
        jPanelConsolaError = new JPanel();
        jScrollPaneConsolaError = new JScrollPane();
        jtaError = new JTextArea();
        jPanel5 = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jButtonEjecutar = new JButton();
        jPanel6 = new JPanel();

        setBackground(new Color(204, 204, 204));

        jPanelConsolaSalida.setBackground(new Color(255, 255, 255));

        jtaSalida.setColumns(20);
        jtaSalida.setEditable(false);
        jtaSalida.setRows(5);
        jScrollPaneConsolaSalida.setViewportView(jtaSalida);

        GroupLayout jPanelConsolaSalidaLayout = new GroupLayout(jPanelConsolaSalida);
        jPanelConsolaSalida.setLayout(jPanelConsolaSalidaLayout);
        jPanelConsolaSalidaLayout.setHorizontalGroup(
            jPanelConsolaSalidaLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(jScrollPaneConsolaSalida, GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
        jPanelConsolaSalidaLayout.setVerticalGroup(
            jPanelConsolaSalidaLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(jScrollPaneConsolaSalida, GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );

        jTabbedPaneConsola.addTab("Salidas", jPanelConsolaSalida);

        jPanelConsolaEntrada.setBackground(new Color(255, 255, 255));

        jtaEntrada.setColumns(20);
        jtaEntrada.setEditable(false);
        jtaEntrada.setRows(5);
        jScrollPaneConsolaEntrada.setViewportView(jtaEntrada);

        GroupLayout jPanelConsolaEntradaLayout = new GroupLayout(jPanelConsolaEntrada);
        jPanelConsolaEntrada.setLayout(jPanelConsolaEntradaLayout);
        jPanelConsolaEntradaLayout.setHorizontalGroup(
            jPanelConsolaEntradaLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(jScrollPaneConsolaEntrada, GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
        jPanelConsolaEntradaLayout.setVerticalGroup(
            jPanelConsolaEntradaLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(jScrollPaneConsolaEntrada, GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );

        jTabbedPaneConsola.addTab("Entradas", jPanelConsolaEntrada);

        jPanelConsolaError.setBackground(new Color(255, 255, 255));

        jtaError.setColumns(20);
        jtaError.setEditable(false);
        jtaError.setRows(5);
        jScrollPaneConsolaError.setViewportView(jtaError);

        GroupLayout jPanelConsolaErrorLayout = new GroupLayout(jPanelConsolaError);
        jPanelConsolaError.setLayout(jPanelConsolaErrorLayout);
        jPanelConsolaErrorLayout.setHorizontalGroup(
            jPanelConsolaErrorLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(jScrollPaneConsolaError, GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
        jPanelConsolaErrorLayout.setVerticalGroup(
            jPanelConsolaErrorLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneConsolaError, GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );

        jTabbedPaneConsola.addTab("Errores", jPanelConsolaError);

        jPanel5.setBackground(new Color(255, 255, 255));
        jPanel5.setBorder(BorderFactory.createTitledBorder("Propiedades del Proyecto"));

        jLabel1.setText("Nombre : Nombre del proyecto");

        jLabel2.setText("Fecha de creacion : ");

        jLabel3.setText("Ultima modificacion :");

        jButtonEjecutar.setText("Ejecutar");

        GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(jButtonEjecutar)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(447, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButtonEjecutar))
        );

        jPanel6.setBackground(new Color(255, 255, 255));
        jPanel6.setBorder(BorderFactory.createTitledBorder("Indicaciones"));

        GroupLayout jPanel6Layout = new GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
                    .addComponent(jTabbedPaneConsola, Alignment.LEADING)
                    .addComponent(jPanel6, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneConsola, GroupLayout.PREFERRED_SIZE, 186, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>


    // Variables declaration - do not modify
    private JButton jButtonEjecutar;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JPanel jPanelConsolaEntrada;
    private JPanel jPanelConsolaError;
    private JPanel jPanelConsolaSalida;
    private JScrollPane jScrollPaneConsolaEntrada;
    private JScrollPane jScrollPaneConsolaError;
    private JScrollPane jScrollPaneConsolaSalida;
    private JTabbedPane jTabbedPaneConsola;
    private JTextArea jtaEntrada;
    private JTextArea jtaError;
    private JTextArea jtaSalida;
    // End of variables declaration

}
