/** 
*This template was generated by littleIDE
**/
/** 
*
*@author CaS
**/

public class nuevaClase{

public nuevaClase(){
    Object o = new Object();
    boolean x= "perro".equals(o);
    
    x=false;    
}


}

//End Class
