/** 
*This template was generated by ECO-IDE
**/

package MongoDB;
/** 
*
*@author cas@
**/

import DTO.Profesor;
import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoException;
import com.mongodb.MongoURI;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Map;

public class MongoDB {

    private static String uriString = "mongodb://eco:eco@ds051447.mongolab.com:51447/ejemplo-mongo";

    private DB database;

    public MongoDB() {

        MongoURI uri = new MongoURI(uriString);

        try {
            database = uri.connectDB();
        } catch (UnknownHostException uhe) {
            System.out.println("UnknownHostException: " + uhe);
        } catch (MongoException me) {
            System.out.println("MongoException: " + me);
        }

    }

    public boolean validarContrasena(String email, String pass) {
        BasicDBObject dbObject = new BasicDBObject();
        dbObject.append("email", email);
        DBCollection locations = locations = database.getCollection("usuarios");
        DBObject results = locations.findOne(new BasicDBObject());
        return results.get("pass").toString().equals(pass);
    }

    public boolean agregarProfesor(Profesor profesor) {
        try {
            BasicDBObject dbObject = profesor.toDBObject();
            DBCollection profesores = database.getCollection("profesores");
            profesores.insert(dbObject);
            return true;
        } catch (Exception e) {
            return false;
        }

    }

    public ArrayList<Profesor> getProfesores(){
        DBCollection profesores = database.getCollection("profesores");
        DBCursor results = profesores.find(new BasicDBObject());
        ArrayList<Profesor> profesorList = new ArrayList<Profesor>();
        while (results.hasNext()) {
                DBObject result = results.next();
                Profesor p = new Profesor();
                p.setCodigo(result.get("codigo").toString());
                p.setNombre(result.get("nombre").toString());
                profesorList.add(p);
            }
        return profesorList;
    }
}

