/** 
*This template was generated by littleIDE
**/
/** 
*
*@author acavaelusuarios
**/

public class gui extends javax.swing.JFrame {

	public gui(){ 

		init();

	} 

private void init(){

   this.setSize(new java.awt.Dimension(300,300));
   this.setPreferredSize(new java.awt.Dimension(300,300));
   setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
   getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

	button0= new javax.swing.JButton();
	getContentPane().add(button0, new org.netbeans.lib.awtextra.AbsoluteConstraints(83,45, 100, 21));
	button0.setText("button0");


	 pack();

	}
	private javax.swing.JButton button0;
///


 public static void main(String args[]) {

	try{

		javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());

	}catch(Exception e){

}


java.awt.EventQueue.invokeLater(new Runnable() {

public void run() {

new gui().setVisible(true);

}

});

}
}

//End Class
