/** 
*This template was generated by littleIDE
**/
/** 
*
*@author acavaelusuarios
**/

public class gui2 extends javax.swing.JFrame {

	public gui2(){ 

		init();

	} 

private void init(){

   this.setSize(new java.awt.Dimension(300,300));
   this.setPreferredSize(new java.awt.Dimension(300,300));
   setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
   getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

	textArea0= new javax.swing.JTextArea();
	getContentPane().add(textArea0, new org.netbeans.lib.awtextra.AbsoluteConstraints(53,40, 100, 41));
	textArea0.setText("textArea0");

	button0= new javax.swing.JButton();
	getContentPane().add(button0, new org.netbeans.lib.awtextra.AbsoluteConstraints(80,131, 100, 21));
	button0.setText("button0");

	label0= new javax.swing.JLabel();
	getContentPane().add(label0, new org.netbeans.lib.awtextra.AbsoluteConstraints(64,184, 100, 21));
	label0.setText("label0");


	 pack();

	}
	private javax.swing.JTextArea textArea0;
	private javax.swing.JButton button0;
	private javax.swing.JLabel label0;
///


 public static void main(String args[]) {

	try{

		javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());

	}catch(Exception e){

}


java.awt.EventQueue.invokeLater(new Runnable() {

public void run() {

new gui2().setVisible(true);

}

});

}
}

//End Class
