/** 
*This template was generated by ECO-IDE
**/

package DTO;

import com.mongodb.BasicDBObject;
/** 
*
*@author cas@
**/

public class Profesor {

    private String nombre;
    private String codigo;

    public Profesor() {
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public BasicDBObject toDBObject() {
        BasicDBObject dbObject = new BasicDBObject();
        dbObject.put("nombre", this.nombre);
        dbObject.put("codigo", this.codigo);
        return dbObject;

    }

    public String toString(){
        return "{ nombre : "+nombre+", codigo : "+codigo+"}";
    }
}
